mapping_sector = {"1": 'Fishery, Agriculture & Forestry' ,
                    "2": 'Foods',
                    "3":'Mining',
                    "4":'Oil and Coal Products',
                    "5":'Construction',
                    "6":'Metal Products',
                    "7":'Glass and Ceramics Products',
                    "8":'Textiles and Apparels',
                    "9":'Pulp and Paper',
                    "10":'Chemicals',
                    "11":'Pharmaceutical',
                    "12":'Rubber Products',
                    "13":'Transportation Equipment',
                    "14":'Iron and Steel',
                    "15":'Nonferrous Metals',
                    "16":'Machinery',
                    "17":'Electric Appliances',
                    "18":'Precision Instruments',
                    "19":'Other Products',
                    "20":'Information & Communication',
                    "21":'Services',
                    "22":'Electric Power and Gas',
                    "23":'Land Transportation',
                    "24":'Marine Transportation',
                    "25":'Air Transportation',
                    "26":'Warehousing and Harbor Transportation',
                    "27":'Wholesale Trade',
                    "28":'Retail Trade',
                    "29":'Banks',
                    "30":'Securities and Commodities Futures',
                    "31":'Insurance',
                    "32":'Other Financing Business',
                    "33":'Real Estate'
                    }